### ISSUE TITLE
Is it possible to use structs?

### ISSUE THREAD

**Issue by Apppppppple** [viceroypenguin/RBush#16]
Trying to implement this in an ecs system (DefaultEcs) and I can't find a way to implement ISpatialData in a struct.

**Comment by Apppppppple** [comment]
![image](https://user-images.githubusercontent.com/19359968/107128034-891aad80-6888-11eb-9143-57176c1febd8.png)

**Comment by viceroypenguin** [comment]
Unfortunately, it's not possible under the C# type system rules due to concerns about the lifetime of the `struct` and making sure all references to the `struct` are handled properly. See dotnet/csharplang#2107 for further discussion on this issue. 

You will need to use a `class` instead of a `struct` to fully implement `ISpatialData` at this time.

**Comment by Apppppppple** [comment]
ah thanks
