### ISSUE TITLE
Question about Inserting Node

### ISSUE THREAD

**Issue by GeoITwinkle** [viceroypenguin/RBush#44]
Thank you very much for converting the JavaScript code and and sharing it on GitHub, it is not easy to find a C# version for R-tree implementation and I appreciate it.
The code runs through and seems to provide same results compared to my original one without using R-tree, but I have a question. 
Below is the code to find the location to insert a new node, but the highlight code seems odd to me. I don't quite follow why it only compares to node.Item[**1**] every time in the for loop. In this case, newArea will never change when iterate through all items. Shouldn't it compare to node.Item[**i**]?
I looked at the similar code in JavaScript version, and it seems it compares to node.Item[i], not node.Item[1].

Thanks,

Xiaoxing

C#
![image](https://user-images.githubusercontent.com/8011074/210013310-c18c8a57-7d5a-4a61-8df4-6fb9be3e043f.png)

JavaScript:
![image](https://user-images.githubusercontent.com/8011074/210013967-3f6e381d-8cfc-42f6-bdf7-4c050b421f8f.png)

**Comment by viceroypenguin** [comment]
Good catch. This bug was introduced in an update 5 months ago attempting to improve performance (by clearing out some LINQ and other potential pitfalls). Thankfully the impact appears to be minor (as most people do bulk load of data, rather than individual data loading or tree merging). I'll get a new version out shortly to fix it.

**Comment by GeoITwinkle** [comment]
Thanks for the quick action and glad that I can help. Happy holidays. -- Xiaoxing
