### ISSUE TITLE
Signed assemblies

### ISSUE THREAD

**Issue by jahav** [viceroypenguin/RBush#51]
I would like to have signed assemblies in the nuget package. Is it something that would be considered?

I am fine with making a PR, probably using this [guide ](https://gist.github.com/cezarypiatek/7d7f837bfe924fe3965482aa702442ef) (the maintainer would need to generate their own secret key though).

**Comment by viceroypenguin** [comment]
> I would like to have signed assemblies in the nuget package. Is it something that would be considered?

Can you please describe the scenario in which you would need signed assemblies. They are not validated in any way in netcore/net5+, so their usage is minimal in modern code.

**Comment by viceroypenguin** [comment]
Very few libraries today are adding support for signed assemblies, and adding signed assemblies creates more issues for other users. This library has existed for 6 years without signed assemblies, and I made an intentional decision at first publishing not to sign the assemblies, based on the prevailing recommendations regarding signed assemblies.

Given the number of users this could negatively impact and the low update-frequency of this library, I'm inclined to deny the request. I don't see any reason someone in an enterprise environment could not clone the repo and sign it internally for their own use.

**Comment by jahav** [comment]
@viceroypenguin Hi, sorry to necro this issue. Would you be amendable to adding another package that would be strongly named in addition to the `RBush` package? E.g. `RBush.Strong`. That way current users of library wouldn't be affected.

I can fork it and make it myself, but I figured I would ask before doing that. I have users asking the strong name https://github.com/ClosedXML/ClosedXML/issues/2423 and few colleagues too.

**Comment by viceroypenguin** [comment]
Published as RBush.Signed v4.0.0; please verify that it is signed.

**Comment by jahav** [comment]
Yes, it is signed. Thank you very much. I am going to fix my build, so it uses RBush.Signed.
